version: 2.1

orbs:
  architect: giantswarm/architect@4.31.0
workflows:
  go-build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: kubectl-gs
          filters:
            tags:
              only: /^v.*/

